### ISSUE TITLE
"Standard and Commerce" option doesn't work with root ID set to -1

### ISSUE THREAD

**Issue by mariajemaria** [Geta/SEO.Sitemaps#131]
With this setup, we get an error in the log file:
`2020-11-18 13:03:34,258 [66] ERROR Geta.SEO.Sitemaps.XML.SitemapXmlGenerator: Error on generating xml sitemap
System.NullReferenceException: Object reference not set to an instance of an object.
   at EPiServer.Core.Internal.ContentInstanceCache.CreateCacheSettings(ContentReference contentLink)
   at EPiServer.Core.ContentProvider.AddContentToCache(IContent content, IEnumerable`1 extraCacheDependencies)
   at EPiServer.Commerce.Catalog.Provider.CatalogContentProvider.GetLanguageBranchesFromDb(ContentReference contentLink, HashSet`1 missingLanguages)
   at EPiServer.Core.Internal.DefaultContentRepository.GetLanguageBranches[T](ContentReference contentLink)
   at Geta.SEO.Sitemaps.XML.SitemapXmlGenerator.GetLanguageBranches(ContentReference contentLink)
   at Geta.SEO.Sitemaps.XML.SitemapXmlGenerator.GenerateXmlElements(IEnumerable`1 pages)
   at Geta.SEO.Sitemaps.Commerce.CommerceAndStandardSitemapXmlGenerator.GetSitemapXmlElements()
   at Geta.SEO.Sitemaps.XML.SitemapXmlGenerator.CreateSitemapXmlContents(Int32& entryCount)
   at Geta.SEO.Sitemaps.XML.SitemapXmlGenerator.Generate(SitemapData sitemapData, Boolean persistData, Int32& entryCount)`

Additionally, the text in the interface is "Root page ID: Sitemap will contain entries for descendant pages of the specified page (-1 means root page).", but in the editor notes, there is a screenshot with the same text, but (0 means root page). From the code, it looks like it should be -1.

**Comment by patkleef** [comment]
Can you let me know what your set up looks like (sitemap settings and managed sites)

**Comment by mariajemaria** [comment]
Please see the following screenshots: 

<img width="617" alt="standard-and-commerce" src="https://user-images.githubusercontent.com/6186324/99786057-53ceb100-2b1e-11eb-863c-3beb163ff969.png">
<img width="607" alt="site-1" src="https://user-images.githubusercontent.com/6186324/99786071-56310b00-2b1e-11eb-92ee-ab7563a4f0ff.png">
<img width="597" alt="site-2" src="https://user-images.githubusercontent.com/6186324/99786078-592bfb80-2b1e-11eb-851c-e8e8048a0fb5.png">

Funny enough, now this did work, but yesterday, not at all. I'll try to run it again, but it might be intermittent. If so, I'll close this until I can provide more info.

**Comment by mariajemaria** [comment]
I'll close this for now, still working!
