### ISSUE TITLE
sitemap generation issue for version 4.0.0

### ISSUE THREAD

**Issue by gatisb** [Geta/SEO.Sitemaps#146]
configuration:
![image](https://user-images.githubusercontent.com/1835493/108820354-c1c6c080-75c4-11eb-93c2-d7d502dcf376.png)
![image](https://user-images.githubusercontent.com/1835493/108820395-cf7c4600-75c4-11eb-999f-7985c9dfb83c.png)
![image](https://user-images.githubusercontent.com/1835493/108820427-dacf7180-75c4-11eb-9ee1-dcc4ea7ae015.png)

we are running two sites, have `StandardAndCommerce` sitemap configured for each
scheduled job results:
![image](https://user-images.githubusercontent.com/1835493/108820547-02bed500-75c5-11eb-88a2-d61bedd5128c.png)

details in log:

```
2021-02-23 10:47:11,551 [160] ERROR Geta.SEO.Sitemaps.XML.SitemapXmlGenerator: Error on generating xml sitemap
System.ArgumentNullException: Value cannot be null.
Parameter name: contentLink
   at EPiServer.Core.Internal.ContentInstanceCache.GetCacheKey(ContentReference contentLink, String language)
   at EPiServer.Core.Internal.ContentInstanceCache.Insert(IContent content, String language, CacheEvictionPolicy evictionPolicy)
   at EPiServer.Core.ContentProvider.AddContentToCache(IContent content, IEnumerable`1 extraCacheDependencies)
   at EPiServer.Commerce.Catalog.Provider.CatalogContentProvider.GetLanguageBranchesFromDb(ContentReference contentLink, HashSet`1 missingLanguages)
   at EPiServer.Core.Internal.DefaultContentRepository.GetLanguageBranches[T](ContentReference contentLink)
   at Geta.SEO.Sitemaps.XML.SitemapXmlGenerator.GetLanguageBranches(ContentReference contentLink)
   at Geta.SEO.Sitemaps.XML.SitemapXmlGenerator.GenerateXmlElements(IEnumerable`1 pages)
   at Geta.SEO.Sitemaps.Commerce.CommerceAndStandardSitemapXmlGenerator.GetSitemapXmlElements()
   at Geta.SEO.Sitemaps.XML.SitemapXmlGenerator.CreateSitemapXmlContents(Int32& entryCount)
   at Geta.SEO.Sitemaps.XML.SitemapXmlGenerator.Generate(SitemapData sitemapData, Boolean persistData, Int32& entryCount)
2021-02-23 10:47:11,572 [160] ERROR Geta.SEO.Sitemaps.XML.SitemapXmlGenerator: Error on generating xml sitemap
System.ArgumentNullException: Value cannot be null.
Parameter name: contentLink
   at EPiServer.Core.Internal.ContentInstanceCache.GetCacheKey(ContentReference contentLink, String language)
   at EPiServer.Core.Internal.ContentInstanceCache.Insert(IContent content, String language, CacheEvictionPolicy evictionPolicy)
   at EPiServer.Core.ContentProvider.AddContentToCache(IContent content, IEnumerable`1 extraCacheDependencies)
   at EPiServer.Commerce.Catalog.Provider.CatalogContentProvider.GetLanguageBranchesFromDb(ContentReference contentLink, HashSet`1 missingLanguages)
   at EPiServer.Core.Internal.DefaultContentRepository.GetLanguageBranches[T](ContentReference contentLink)
   at Geta.SEO.Sitemaps.XML.SitemapXmlGenerator.GetLanguageBranches(ContentReference contentLink)
   at Geta.SEO.Sitemaps.XML.SitemapXmlGenerator.GenerateXmlElements(IEnumerable`1 pages)
   at Geta.SEO.Sitemaps.Commerce.CommerceAndStandardSitemapXmlGenerator.GetSitemapXmlElements()
   at Geta.SEO.Sitemaps.XML.SitemapXmlGenerator.CreateSitemapXmlContents(Int32& entryCount)
   at Geta.SEO.Sitemaps.XML.SitemapXmlGenerator.Generate(SitemapData sitemapData, Boolean persistData, Int32& entryCount)
```

**Comment by gatisb** [comment]
@patkleef your provided test package works:

![image](https://user-images.githubusercontent.com/1835493/110487247-10607880-80f6-11eb-909f-e59571119109.png)


please publish release for it

**Comment by patkleef** [comment]
@gatisb version 4.0.1 now available.
